apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-app
  name: hello-app
spec:
  ports:
  - port: 85
    protocol: TCP
    targetPort: 8080
    nodePort: 32100
  selector:
    app: hello-app
  type: NodePort
status:
  loadBalancer: {}
